spring:
  application:
    name: desafio

  datasource:
    url: jdbc:postgresql://localhost:5432/Desafio
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  security:
    token:
      secret: meu-segredo-super-secreto-e-longo-para-gerar-tokens

logging:
  level:
    root: WARN
    com.julio.desafio: INFO